import { Company, Genre, Series } from "../../next-type-d";

export const series: Series[] = [
  {
    adult: false,
    backdrop_path: "/wNKwOtq27yfN13SKKV07NwkpBA3.jpg",
    genre_ids: [18, 10765, 10759],
    id: 80752,
    origin_country: ["CA"],
    original_language: "en",
    original_name: "See",
    overview:
      "A virus has decimated humankind. Those who survived emerged blind. Centuries later when twins are born with the mythic ability to see, their father must protect his tribe against a threatened queen.",
    popularity: 276.315,
    poster_path: "/1kZdBrH1C07Zf2131QUpmju3kO6.jpg",
    first_air_date: "2019-11-01",
    name: "See",
    vote_average: 8.2,
    vote_count: 2125,
  },
  {
    adult: false,
    backdrop_path: "/t73x5Pb81mIGZR417aeGwbkR520.jpg",
    genre_ids: [18, 80],
    id: 86430,
    origin_country: ["US"],
    original_language: "en",
    original_name: "Your Honor",
    overview:
      "New Orleans judge Michael Desiato is forced to confront his own deepest convictions when his son is involved in a hit and run that embroils an organized crime family.",
    popularity: 49.603,
    poster_path: "/1rWWgTEDFdV330aLgCoaq7I56lk.jpg",
    first_air_date: "2020-12-06",
    name: "Your Honor",
    vote_average: 8.169,
    vote_count: 1378,
  },
  {
    adult: false,
    backdrop_path: "/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
    genre_ids: [80, 18],
    id: 71446,
    origin_country: ["ES"],
    original_language: "es",
    original_name: "La Casa de Papel",
    overview:
      "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
    popularity: 138.054,
    poster_path: "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    first_air_date: "2017-05-02",
    name: "Money Heist",
    vote_average: 8.26,
    vote_count: 17747,
  },
];
//63333 87108
//1396 1399 70523

export const companies: Company[] = [
  {
    description: "",
    headquarters: "New York City, New York",
    homepage: "https://www.hbo.com",
    id: 3268,
    logo_path: "/tuomPhY2UtuPTqqFnKMVHvSb724.png",
    name: "HBO",
    origin_country: "US",
    parent_company: null,
  },
  {
    description: "",
    headquarters: "Los Gatos, California",
    homepage: "https://www.netflix.com",
    id: 178464,
    logo_path: "/tyHnxjQJLH6h4iDQKhN5iqebWmX.png",
    name: "Netflix",
    origin_country: "US",
    parent_company: null,
  },
  {
    description: "",
    headquarters: "Higashi-Shimbashi, Minato, Tokyo",
    homepage: "https://www.hulu.jp",
    id: 140361,
    logo_path: "/fibZ29NMQS46v7vXZ1Y3uXL7Q39.png",
    name: "Hulu Japan",
    origin_country: "JP",
    parent_company: null,
  },
  {
    description: "",
    headquarters: "Emeryville, California",
    homepage: "http://www.pixar.com",
    id: 3,
    logo_path: "/1TjvGVDMYsj6JBxOAkUHpPEwLf7.png",
    name: "Pixar",
    origin_country: "US",
    parent_company: {
      name: "Walt Disney Pictures",
      id: 2,
      logo_path: "/wdrCwmRnLFJhEoH8GSfymY85KHT.png",
    },
  },
  {
    description: "",
    headquarters: "Broadcasting House, London, England",
    homepage: "https://bbc.co.uk",
    id: 3324,
    logo_path: "/dqT3yOTlfJRmtvk52Ccd1O6dZ0A.png",
    name: "BBC",
    origin_country: "GB",
    parent_company: null,
  },
  {
    description: "",
    headquarters: " Burbank, California",
    homepage: "https://www.marvel.com/movies",
    id: 420,
    logo_path: "/hUzeosd33nzE5MCNsZxCGEKTXaQ.png",
    name: "Marvel Studios",
    origin_country: "US",
    parent_company: null,
  },
  {
    description: "",
    headquarters: "Glendale, California",
    homepage: "",
    id: 15935,
    logo_path: "/25xmKjrZS3TJMYa1RvxZ2qcMHHX.png",
    name: "Walt Disney Imagineering",
    origin_country: "US",
    parent_company: null,
  },
  {
    description: "",
    headquarters: "Universal City, California",
    homepage: "http://www.universalpictures.com/",
    id: 33,
    logo_path: "/8lvHyhjr8oUKOOy2dKXoALWKdp0.png",
    name: "Universal Pictures",
    origin_country: "US",
    parent_company: null,
  },
];