import "./globals.css";
import type { Metadata } from "next";
import Header from "./components/Global/Header";
import Providers from "./components/Global/Providers";
import Footer from "./components/Global/Footer";


export const metadata: Metadata = {
  title: "Movie City",
  description: "Movie City id Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body
          className={`max-w-[1440px] mx-auto min-h-screen`}
          >
          <Providers>
          <Header />
          <main className="ms-auto pt-4 px-2 min-h-screen flex flex-col md:w-[calc(100%-200px)]">
            {children}
            <Footer />
          </main>
      </Providers>
        </body>
    </html>
  );
}
