import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Global/Header";
import Providers from "./components/Global/Providers";
import Footer from "./components/Global/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movie City",
  description: "Movie City id Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`max-w-[1440px] mx-auto min-h-screen  ${inter.className}`}
        >
          <Header />
          <main className="ms-auto pt-4 px-2 min-h-screen flex flex-col md:w-[calc(100%-180px)]">
            {children}
            <Footer />
          </main>
        </body>
      </Providers>
    </html>
  );
}
